/* Memory-read canary NIF for Tyn (directions/TLB_CANARY.md).
 *
 * A large STABLE buffer, allocated + filled ONCE, then read in a tight loop and
 * compared to its known pattern. PURE READER — the measurement loop allocates
 * nothing and never writes the buffer, so it measures the transient READ, not
 * churn (churn is generated by separate Elixir workers). If a read transiently
 * returns a wrong byte, it's the mapping/paging path, not the allocator or hash
 * machinery.
 *
 * The compare is done AS the byte is read, so the captured `stale` value is the
 * value from the SAME read that detected the mismatch — not a re-read (which
 * recovers). This is the equivalent of "watch the corrupted address": on a
 * misread we return the offset, the stale byte actually read, the expected byte,
 * and the buffer's address, so the stale bytes can be matched against a
 * recently-freed mapping (frame-reuse) vs zero (unmapped) vs garbage.
 *
 * read(Outer) -> {Bad, LastOff, LastStale, LastExp, BufAddr, StaleCtxHex}
 *   Bad     = number of the Outer full-buffer scans that saw a stale byte
 *   LastOff/Stale/Exp = the last captured misread (offset, value read, expected)
 *   BufAddr = &buf[0]        StaleCtxHex = 16 bytes read around LastOff (as read)
 *
 * Verify in the disassembly that the inner read is a real load each iteration
 * (buf is volatile) and that the expected value is computed, not memory-read.
 *
 * Erlang side: src/erl/canary.erl calls erlang:load_nif("canary", 0). */
#include <erl_nif.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#define CANARY_SIZE (1024 * 1024)   /* 1 MiB stable buffer */

static uint8_t *g_buf = NULL;

/* Deterministic, offset-dependent, non-trivial pattern (so stale data from a
 * different mapping is very unlikely to accidentally match). */
static inline uint8_t pat(size_t off) {
    return (uint8_t)(0x9Eu * (uint32_t)(off + 1) + (uint32_t)(off >> 3) + 0x5Au);
}

static int cnry_load(ErlNifEnv *env, void **priv, ERL_NIF_TERM info) {
    (void)env; (void)priv; (void)info;
    g_buf = (uint8_t *)malloc(CANARY_SIZE);
    if (!g_buf) return 1;
    for (size_t i = 0; i < CANARY_SIZE; i++) g_buf[i] = pat(i);
    return 0;
}

static ERL_NIF_TERM read_nif(ErlNifEnv *env, int argc, const ERL_NIF_TERM argv[]) {
    long outer;
    if (argc != 1 || !enif_get_long(env, argv[0], &outer)) return enif_make_badarg(env);
    if (!g_buf) return enif_make_badarg(env);

    volatile uint8_t *b = g_buf;   /* volatile => the compiler must load each time */
    long bad = 0;
    long last_off = -1, last_stale = -1, last_exp = -1;
    uint8_t ctx[16]; memset(ctx, 0, sizeof ctx);

    for (long it = 0; it < outer; it++) {
        for (size_t off = 0; off < CANARY_SIZE; off++) {
            uint8_t v = b[off];               /* the read under test */
            if (v != pat(off)) {              /* expected is computed, not read */
                bad++;
                last_off = (long)off; last_stale = v; last_exp = pat(off);
                /* capture 16 bytes around the misread, AS READ (same staleness) */
                size_t start = off >= 4 ? off - 4 : 0;
                for (int k = 0; k < 16 && start + k < CANARY_SIZE; k++)
                    ctx[k] = b[start + k];
                break;                        /* one capture per scan */
            }
        }
    }

    char hex[33];
    static const char *H = "0123456789ABCDEF";
    for (int k = 0; k < 16; k++) { hex[2*k] = H[ctx[k] >> 4]; hex[2*k+1] = H[ctx[k] & 15]; }
    hex[32] = 0;

    ERL_NIF_TERM tup[6] = {
        enif_make_long(env, bad),
        enif_make_long(env, last_off),
        enif_make_long(env, last_stale),
        enif_make_long(env, last_exp),
        enif_make_ulong(env, (unsigned long)g_buf),
        enif_make_string(env, hex, ERL_NIF_LATIN1),
    };
    return enif_make_tuple_from_array(env, tup, 6);
}

static ErlNifFunc nif_funcs[] = {
    {"read", 1, read_nif},
};

ERL_NIF_INIT(canary, nif_funcs, cnry_load, NULL, NULL, NULL)
